princessbook/booktique

src/app/bookclubs/detail/[id]/page.tsx
src/app/bookclubs/page.tsx
src/utils/time.ts

북클럽 전체 목록 페이지, 
상세 페이지 UI 구현 및 일부 DB 연결, 
utils에 time.ts파일 추가
closed #12 
어떤 변경 사항이 있나요?

[현미] 북클럽 전체 목록 페이지, 상세 페이지 UI 구현 및 일부 DB 연결

---

src/app/bookclubs/[id]/ClubMemberProfile.tsx
src/app/bookclubs/[id]/page.tsx

clubmemberprofile 컴포넌트 이름 변경
맥에서 파일 이름 바꾸다 보면 이상한 문자가 들어가는 경우가 있음
파일 앞에 ?<<가 생김 
어떤 변경 사항이 있나요?

[fix] : clubmemberprofile 컴포넌트 이름 변경

---

src/app/bookclubs/ClubAdminProfile.tsx
src/app/globals.css
src/app/readbook/ClubList.tsx
src/app/readbook/ProgressBar.tsx
src/app/readbook/ReadButton.tsx
src/app/readbook/[id]/EndButton.tsx
src/app/readbook/[id]/EndModal.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/BookInfo.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx
src/app/readbook/[id]/[save]/page.tsx
src/app/readbook/[id]/page.tsx
src/app/readbook/layout.tsx
src/app/readbook/page.tsx

슬라이드,ui 수정, 책읽기 종료하기클릭시 기록할 수 있는 페이지 이동 및 데이터 받는 로직 완료, 책 읽기 종료시 db업데이트 추가 , 페이지ui기본 세팅
closed #60 
어떤 변경 사항이 있나요?

[대연] - #60 : 슬라이드,ui 수정, 책읽기 종료하기클릭시 기록할 수 있는 페이지 이동 및 데이터 받는 로직 완료, 책 읽기 종료시 db업데이트 추가 , 페이지ui기본 세팅

---

src/app/readbook/ClubList.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx
src/app/readbook/[id]/[save]/page.tsx
src/app/readbook/page.tsx

로그인 하지 않았을 때 상태 추가
closed #72 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] -#72 css수정

---

public/fail.svg
public/success.svg
src/app/login/page.tsx
src/app/register/[id]/avatar/page.tsx
src/app/register/[id]/page.tsx
src/common/ToastUi.tsx
src/components/login/LoginForm.tsx
src/components/nickname/MyNicknameForm.tsx
src/components/register/RegisterForm.tsx

회원가입,nickname,avatar폴더변경
toast창 만들기
validation처리
#77 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]- 회원가입,nickname,avatar폴더변경및 toast창 만들기 및 validation

---

src/app/readbook/ClubList.tsx
src/app/readbook/ProgressBar.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/EndModal.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/SaveBookInfo.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx
src/app/readbook/[id]/[save]/SaveProgressBar.tsx
src/app/readbook/[id]/[save]/Timer.tsx
src/app/readbook/[id]/[save]/page.tsx
src/app/readbook/[id]/page.tsx
src/app/readbook/page.tsx

[feat] - 타이머 기능추가하기 , [fix] - 디자인 수정
closed #79 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연]-#79 [feat] - 타이머 기능추가하기 , [fix] - 디자인 수정

---

src/app/myclubinfo2/page.tsx
src/components/myclubinfo2/QuizArchiving.tsx
src/components/quiz/QuizAnswer.tsx
src/components/quiz/QuizModal.tsx

내 북클럽 찾기에 퀴즈 아카이빙 추가
퀴즈 유효성 검사 추가
closed #86
어떤 변경 사항이 있나요?

#86 [feat] : 내 북클럽 찾기에 퀴즈 아카이빙 추가, 퀴즈 유효성 검사 추가

---

src/components/quiz/QuizModal.tsx

아까 반영 안 됐던 거 추가
closed #86 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#86 [feat] : 퀴즈 유효성 검사 추가2

---

src/components/myclubinfo2/SentenceStorage.tsx

문장저장소 삭제후에 버튼바로 바뀌게
#93 
closed #93 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - 문장저장소 삭제후에 버튼바로 바뀌게

---

src/app/myclubinfo2/page-client.tsx
src/components/mypage/MyBookClub.tsx
src/utils/userAPIs/authAPI.ts

archive가 false 일때가 진행중인걸로 바꿈 
closed #100 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix]:archive가 false일 때가 진행중

---

src/app/globals.css
src/app/readbook/ClubList.tsx
src/components/myclubinfo2/Members.tsx
src/components/mypage/ProfileDetail.tsx
src/store/zustandStore.ts

닉네임만 변경해도 수정됌. 사진만 변경해도 수정댐. 아마도.
slider도 아주살짝 고쳤음 ㅎㅎ
closed #103  
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix]:마이페이지 프로필사진 선택안하면 수정 안되는 문제 해결

---

src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
src/utils/postAPIs/postAPI.ts

#56 
디자인, 유효성, 추가 필요합니다..
일단 댓글도 빠르게 구현부터 하겠습니다..!
closed #56 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#56 [승희]: 자유게시판 구현

---

src/app/readbook/ClubList.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/EndModal.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx
src/app/readbook/[id]/[save]/Timer.tsx
src/app/readbook/[id]/page.tsx

타이머 0초부터 시작하게 변경하고, 새로고침 시 타이머 유지  
closed #108 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #108

---

src/app/page.tsx

로그인여부에 따라 루트page 리다이렉트
closed #117 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#117 [fix]-로그인여부에 따라 루트page 리다이렉트

---

src/app/myclubinfo2/board/detail/[postId]/page.tsx
src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/app/myclubinfo2/page.tsx

페이지컴포넌트 이름 변경
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희] - 컴포넌트 이름 변경

---

src/app/myclubinfo2/board/detail/[postId]/page.tsx
src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: 에러 수정

---

src/app/chat/[id]/ChatInput.tsx
src/app/chat/[id]/page.tsx
src/app/myclubinfo2/page-client.tsx
src/app/page.tsx
src/app/readbook/[id]/[save]/page.tsx
src/app/readbook/page.tsx
src/hooks/fetchDB.ts

타입에러 수정 및 경로 수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[예린]- [mod]: 타입에러 수정 및 경로 수정

---

public/backArrow.svg
src/app/chat/[id]/ChatInput.tsx
src/app/chat/[id]/page.tsx
src/app/globals.css
src/app/register/set-profile-image/page.tsx
src/common/Input.tsx
src/common/ToastUi.tsx
src/components/login/LoginForm.tsx
src/components/myclubinfo2/SentenceStorage.tsx
src/components/nickname/MyNicknameForm.tsx
src/components/realtime/ChatMessages.tsx
src/components/realtime/ListMessages.tsx
src/components/realtime/OtherMessage.tsx
src/components/register/RegisterForm.tsx
src/utils/api/authAPI.ts
src/utils/nicknameGenerator.ts
src/utils/validation.ts

realtime 나와 남이 친채팅 구별, 코드정리및 파일분리
#128 
closed #128 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - #128 [feat,fix] realtime 나와 남이 친채팅 구별하고 코드정리및 파일분리

---

src/app/register/set-profile-image/page.tsx
src/components/myclubinfo2/SentenceModal.tsx

모달닫히는거 해결
#141 
closed #141 
어떤 변경 사항이 있나요?
oast message나오기전에 모달닫히는거 해결
```
|기능|스크린샷|
```

[철균] - #141 [fix] : toast message나오기전에 모달닫히는거 해결

---

package.json
src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/boardDetail/ArticleTimeStamp.tsx
src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
src/hooks/Board/useRelativeTime.tsx
src/lib/types/supabase.ts
tailwind.config.ts
yarn.lock

유효성검사, list css 변경했습니다.
#140
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희] - Board 유효성 검사 추가, postlist css 변경

---

src/app/bookclubs/ClubAdminProfile.tsx
src/app/chat/[id]/ChatInput.tsx
src/app/globals.css
src/components/realtime/ListMessages.tsx
src/components/realtime/Message.tsx
src/components/realtime/OtherMessage.tsx

채팅 최신순으로 정렬
scrollbar두개중복 하나로 해결
#148 
closed #148 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - #148 [feat,fix]:채팅 최신순으로 정렬 및 scrollbar두개중복 하나로 해결

---

package.json
src/components/quiz/QuizAnswer.tsx
src/components/quiz/QuizContainer.tsx
src/components/quiz/QuizModal.tsx
src/components/quiz/QuizQuestion.tsx
src/components/quiz/QuizShortAnswer.tsx
yarn.lock

[현미] - 퀴즈 정답제출하기 기능 추가

---

src/app/chat/[id]/ChatInput.tsx
src/app/globals.css
src/components/mypage/ProfileDetail.tsx
src/components/realtime/ChatMessages.tsx
src/components/realtime/ChatPresence.tsx
src/components/realtime/ListMessages.tsx
src/components/realtime/Message.tsx
src/components/realtime/OtherMessage.tsx
src/utils/timeUtils.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - #154 [feat,fix] realtime 디자인 및 클럽명띄우기

---

src/app/myclubinfo2/page-client.tsx
src/app/mypage/mybookclubs/page.tsx
src/app/mypage/page.tsx
src/app/readbook/ProgressBar.tsx
src/components/myclubinfo2/ClubBook.tsx
src/components/myclubinfo2/HomeTab.tsx
src/components/myclubinfo2/Members.tsx
src/components/mypage/AllMyBookClubs.tsx
src/components/mypage/LogoutButton.tsx
src/components/mypage/MySentencesStore.tsx
src/components/mypage/ProfileDetail.tsx
src/components/realtime/OtherMessage.tsx

프로그레스바 애니메이션 살짝 추가했는데 (transition-width duration-1000 ease-out) 어때요. ㅋㅋㅋ. ㅋㅋ.
북클럽없을때 NonMyClub 컴포넌트 안나오길래 수정했음요
마이페이지 디자인도 좀 바꿈요
마이페이지에서 내 북클럽 더보기 누르기전엔 4개만 보이고 더보기 누르면 전체 다보이게 하고싶은데
같은 컴포넌트 재활용 쓰고싶은데 다른 페이지라 어캐해야할지 모르겠음요 그래서 그냥 똑같은거 두개 씀요.ㅠ 방법알면좀알려주셈요 ㅠ
이것저것해서 짬뽕임 죄송요
closed #155 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[예린]- 내북클럽 없을때 수정, 마이페이지 내북클럽 더보기 만들기..

---

src/app/myclubinfo2/board/detail/[postId]/page.tsx
src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
src/utils/api/postCommentAPIs/commentAPI.ts

#140 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: 글쓰기 스타일 추가, 댓글 개발중

---

src/components/quiz/QuizModal.tsx

[fix] : quiz 주관식 입력 안되는 버그 해결

---

src/app/myclubinfo2/board/detail/[postId]/page.tsx
src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/app/myclubinfo2/page-client.tsx
src/app/mypage/mybookclubs/page.tsx
src/app/mypage/page.tsx
src/app/readbook/ProgressBar.tsx
src/components/myclubinfo2/ClubBook.tsx
src/components/myclubinfo2/HomeTab.tsx
src/components/myclubinfo2/Members.tsx
src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
src/components/mypage/AllMyBookClubs.tsx
src/components/mypage/LogoutButton.tsx
src/components/mypage/MySentencesStore.tsx
src/components/mypage/ProfileDetail.tsx
src/components/quiz/QuizModal.tsx
src/utils/api/postCommentAPIs/commentAPI.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[merge] - 배포 업데이트 확인

---

src/components/mypage/AllMyBookClubs.tsx
src/components/mypage/MyBookClub.tsx

마이페이지 내 북클럽 최신순 정렬...
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[예린] - 북클럽 최신순 정렬

---

src/app/globals.css
src/app/layout.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

배포테스트(높이조정)

---

src/app/myclubinfo2/board/detail/[postId]/page.tsx
src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
src/components/myclubinfo2/board/boardDetail/ArticleCommentInput.tsx
src/lib/types/supabase.ts
src/utils/api/postCommentAPIs/commentAPI.ts

댓글 만들었습니다.
근데 하단 네비게이션바가 레이아웃이라, 디자인처럼 레이아웃을 사라지게 해야하는디 고민이네요
걍 absolute로 가려버릴까요? 인풋창으로 ㅋㅋㅋ
#140 
#112 
closed #140 
closed #112 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: 댓글 기능 구현, 스타일 추가

---

src/app/layout.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - #165 [fix] : 전체높이조정

---

src/app/layout.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - main으로 이동

---

src/app/readbook/ClubList.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/Timer.tsx
src/app/readbook/[id]/page.tsx
src/components/footer/page.tsx
src/lib/types/supabase.ts

[fix,feat] - 새로고침시 푸터 클릭해제 수정, 알람테스트
closed #170 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #170 [fix,feat] - 새로고침시 푸터 클릭해제 수정, 알람테스트

---

src/app/layout.tsx
src/app/readbook/ClubList.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/MemberList.tsx
src/app/readbook/[id]/[save]/Timer.tsx
src/app/readbook/[id]/page.tsx
src/components/footer/page.tsx
src/lib/types/supabase.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - Main이동

---

src/app/readbook/[id]/BookInfo.tsx
src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx

#170 배포테스트
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #170 배포테스트

---

src/app/layout.tsx
src/components/footer/page.tsx

모바일 가로크기 고정해제 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[style] : 모바일 고정 width 제한 품

---

src/app/layout.tsx

하단 nav바에 컨텐츠 가려지는 이슈 해결
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[style] : 하단 nav바에 컨텐츠 가려지는 이슈 해결

---

src/app/layout.tsx
src/components/footer/page.tsx
tailwind.config.ts

태블릿,pc에서 모바일 크기로 보이게 조정, bottom navigation 스타일 수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[style] : 태블릿,pc에서 모바일 크기로 보이게 조정, bottom navigation 스타일 수정

---

src/app/bookclubs/ClubSearch.tsx
src/app/bookclubs/page.tsx
src/app/layout.tsx

개설하기 버튼 위치를 fixed이면서 부모요소를 벗어나지 않게 변경했습니다
북클럽 찾기에 돋보기 아이콘과 x 버튼을 추가했습니다
폰트 사이즈를 수정했습니다.
closed #183 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[현미] Feature/#183 북클럽 찾기 페이지 스타일 및 기능 추가

---

src/components/quiz/QuizAnswer.tsx
src/components/quiz/QuizContainer.tsx
src/components/quiz/QuizModal.tsx
src/components/quiz/QuizQuestion.tsx
src/components/quiz/QuizShortAnswer.tsx

퀴즈 객관식 답안 최소입력 개수 제한
개설하기 버튼 위치 변경 
자잘한  버그 및 스타일 수정
closed #187 
어떤 변경 사항이 있나요?

[현미] - [fix/#187] : 퀴즈 객관식 답안 최소입력 개수 제한, 자잘한  버그 및 스타일 수정

---

src/app/readbook/ClubList.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/EndButton.tsx
src/app/readbook/[id]/[save]/SaveBookInfo.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx

[fix] - css수정, 모임시작 로직 변경,책 읽기 버튼 주석처리, 카드 클릭시 이동
closed #170 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #170 [fix] - css수정, 모임시작 로직 변경,책 읽기 버튼 주석처리, 카드 클릭시 이동

---

src/components/myclubinfo2/QuizArchiving.tsx
src/components/quiz/MultipleChoiceQuizComponent.tsx
src/components/quiz/QuizContainer.tsx
src/components/quiz/ShortQuizComponent.tsx

[현미] Fix/#191 퀴즈 버그 및 스타일 수정

---

src/app/readbook/ClubList.tsx
src/app/readbook/[id]/BookInfo.tsx
src/app/readbook/[id]/EndButton.tsx
src/app/readbook/[id]/[save]/SaveBookInfo.tsx
src/app/readbook/[id]/[save]/SaveCard.tsx
src/components/myclubinfo2/QuizArchiving.tsx
src/components/quiz/MultipleChoiceQuizComponent.tsx
src/components/quiz/QuizAnswer.tsx
src/components/quiz/QuizContainer.tsx
src/components/quiz/QuizModal.tsx
src/components/quiz/QuizQuestion.tsx
src/components/quiz/QuizShortAnswer.tsx
src/components/quiz/ShortQuizComponent.tsx

전 pr에서 vercel배포 오류 부분 수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - [fix] - 배포에러수정

---

src/app/readbook/[id]/BookInfo.tsx
src/components/myclubinfo2/board/boardDetail/ArticleTimeStamp.tsx
src/lib/types/supabase.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] [fix] - 타입수정

---

src/app/readbook/[id]/BookInfo.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix]- 모든멤버로 수정

---

src/app/myclubinfo2/board/posting/[postId]/page.tsx
src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/boardDetail/ArticleTimeStamp.tsx
src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
src/components/myclubinfo2/board/posting/PhotoSection.tsx
src/lib/types/supabase.ts
src/utils/nicknameGenerator.ts
src/utils/postAPIs/postAPI.ts

#188 
closed #188 
어떤 변경 사항이 있나요?
자유게시판 썸네일 추가 했습니다
```
|기능|스크린샷|
```

[승희]: 자유게시판 썸네일 추가 기능 구현

---

src/app/(navigationBar)/bookclubs/create/page.tsx
src/app/bookclubs/ClubSearch.tsx

북클럽 썸네일 부활
개설하기 버튼 안 나오는 이슈 해결
어떤 변경 사항이 있나요?

현미 - [Fix/bookclubs] : 북클럽 썸네일 부활, 개설하기 버튼 안 나오는 이슈 해결

---

src/app/globals.css
src/common/Input.tsx
src/components/myclubinfo2/SentenceStorage.tsx
src/components/nickname/MyNicknameForm.tsx
src/components/realtime/ChatPresence.tsx
src/components/register/RegisterForm.tsx
src/utils/api/authAPI.ts
src/utils/validation.ts

input password 해결, 소셜로그인해결, input close버튼 위치조정
#211 
closed #211 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] : 이슈사항들 해결하기

---

src/app/globals.css
src/components/realtime/ChatPresence.tsx
src/components/realtime/ListMessages.tsx
src/utils/api/authAPI.ts

배포주소 구글소셜로그인
채팅방 높이조정
#211 
closed #211 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - #211 [fix] : 배포주소 구글소셜로그인 및 채팅방 높이조정

---

src/app/globals.css
src/app/page.tsx
src/components/realtime/ChatPresence.tsx
src/components/realtime/ListMessages.tsx
src/utils/api/authAPI.ts

배포주소 구글소셜로그인 및 채팅방 높이조정

---

src/components/myclubinfo2/board/Board.tsx
src/components/myclubinfo2/board/posting/PhotoSection.tsx

#221 
#220 
댓글 수 표기는 성능이슈때문에 잠시 미뤘습니다. 나머진 전부 해결했어요
closed #220 #221 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: 자유게시판 글 목록 유저프로필 캐시 제거, 글 목록 높이 유동적으로 변경, 인풋 확장자 제한

---

src/components/footer/page.tsx

closed #225 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #225 [design] - 푸터 border말구 그림자로 상단변경

---

src/app/globals.css
src/components/myclubinfo2/SentenceStorage.tsx
src/components/myclubinfo2/SentenceUser.tsx
src/components/realtime/ChatMessages.tsx
src/components/realtime/ListMessages.tsx
src/components/realtime/LoadMoreMessages.tsx
src/lib/constant/index.ts
src/lib/utils.ts
src/store/InitMessages.tsx
src/store/messages.ts

채팅창 더보기누르면10개씩더나오는기능
폰트추가
#237 
#237 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-채팅창 더보기누르면10개씩더나오는기능, 폰트추가

---

src/components/mypage/profile/Profile.tsx

[fix]-마이페이지에 있을 때 알람 뜨는지 테스트
closed #248 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#248 [fix]-마이페이지에 있을 때 알람 뜨는지 테스트

---

src/app/(navigationBar)/mypage/layout.tsx
src/components/mypage/profile/Profile.tsx

[fix]-layout테스트
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] #251 [fix]-layout테스트

---

src/app/(navigationBar)/mypage/layout.tsx
src/components/mypage/profile/Profile.tsx

[[fix]-layout테스트](https://github.com/princessbook/booktique/commit/6e6efa8d7a8a893bd421d28e07ff6f6204a0ba92)

[fix]-layout테스트

---

src/app/(navigationBar)/mypage/layout.tsx

#251 타임아웃 1초에서 3초로 변경하고 테스트
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #251 타임아웃 1초에서 3초로 변경하고 테스트

---

src/app/login/action.ts
src/middleware.ts
src/utils/middlewares/authToken.ts
src/utils/middlewares/chain.ts
src/utils/middlewares/middleware.ts
src/utils/middlewares/protectRoute.ts

로그인하지않을때 페이지 이동을막음(middleware수정)
#254 
closed #254 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균] - 로그인하지않을때 페이지 이동을막음(middleware수정)

---

src/app/(navigationBar)/my-clubs/[clubId]/info/page.tsx
src/app/(navigationBar)/mypage/mybookclubs/page.tsx
src/app/(navigationBar)/mypage/page.tsx
src/app/(navigationBar)/readbook/[id]/MemberList.tsx
src/components/my-clubs/info/ClubBook.tsx
src/components/my-clubs/info/HomeTab.tsx
src/components/mypage/clubs/AllMyBookClubs.tsx
src/components/mypage/clubs/BookClubItem.tsx
src/components/mypage/clubs/MyBookClub.tsx
src/components/mypage/profile/LogoutButton.tsx
src/components/mypage/profile/Profile.tsx
src/components/mypage/profile/ProfileDetail.tsx
src/components/mypage/sentences/AllMySentences.tsx
src/components/mypage/sentences/MySentencesStore.tsx
src/components/mypage/sentences/SentenceItem.tsx
src/utils/userAPIs/storageAPI.ts

406에러 뜨는거 없앤듯 ;;
디자이너님이 확인해달라는 디자인 수정함;;
info를 서버로 만들어서 하위 컴포넌트도 서버로 만들 예정임 ;;
closed #256 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[예린] - 디자인 수정 및 에러 해결

---

src/components/login/LoginForm.tsx
src/utils/api/authAPI.ts
src/utils/getCallBackURL.ts

배포,로컬둘다 소셜로그인
#263 
closed #263 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#263 [fix]: 배포,로컬둘다 소셜로그인

---

src/utils/getCallBackURL.ts

배포주소 소셜로그인테스트

---

src/components/login/LoginForm.tsx
src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구

---

src/components/login/LoginForm.tsx
src/utils/api/authAPI.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

모바일에서 셀렉트 바 디자인 없애기

---

src/middleware.ts
src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구2

---

src/middleware.ts
src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구3

---

src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구5

---

src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구7

---

src/components/login/LoginForm.tsx
src/utils/api/authAPI.ts
src/utils/getCallBackURL.ts

배포주소 소셜로그인테스트 원상복구8

---

src/utils/api/authAPI.ts

배포주소 소셜로그인테스트 원상복구9

---

src/components/my-clubs/board/Board.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix]: posting page 리다이렉트 수정

---

src/app/(navigationBar)/my-clubs/[clubId]/sentences/page.tsx
src/components/my-clubs/sentences/Sentences.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

철균-#302 [rafactor]: 무한루프에러

---

src/app/provider.tsx
src/components/my-clubs/board/Board.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#302 [fix]: 스타일변경

---

src/app/(navigationBar)/layout.tsx
src/app/(navigationBar)/readbook/ClubList.tsx
src/app/(navigationBar)/readbook/ReadButton.tsx
src/app/(navigationBar)/readbook/[id]/EndModal.tsx
src/app/(navigationBar)/readbook/[id]/MemberList.tsx
src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
src/components/navigationBar/page.tsx
src/lib/types/supabase.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#277 [fix] - 배포전 임시로 버튼막기

---

src/components/my-clubs/info/HomeTab.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

제발 성능개선해주세요..

---

src/app/(navigationBar)/readbook/ClubList.tsx
src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
src/app/(navigationBar)/readbook/[id]/[save]/page.tsx

[fix] - 책읽기페이지 모바일 환경에서 버튼 안보이는 현상 수정,[fix] - 콘솔삭제
어떤 변경 사항이 있나요?
- [x ] CSS 등 사용자 UI 디자인 변경
```
|기능|스크린샷|
```

[대연]-#277 [fix] - 책읽기페이지 모바일 환경에서 버튼 안보이는 현상 수정,[fix] - 콘솔삭제

---

src/app/(navigationBar)/bookclubs/create/page.tsx
src/app/(navigationBar)/bookclubs/create/search/SearchModal.tsx
src/app/(navigationBar)/my-clubs/[clubId]/posts/board/detail/[postId]/page.tsx
src/app/(navigationBar)/my-clubs/[clubId]/posts/board/posting/[postId]/page.tsx
src/components/common/HeaderWithBack.tsx
src/components/my-clubs/board/boardDetail/ArticleCommentInput.tsx
src/components/my-clubs/board/boardDetail/BoardDetailArticle.tsx
src/utils/postAPIs/postAPI.ts
src/utils/userAPIs/storageAPI.ts

#321 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: Board 디자인 수정중

---

src/app/(navigationBar)/my-clubs/[clubId]/posts/board/posting/[postId]/page.tsx
src/components/my-clubs/board/boardDetail/BoardDetailArticle.tsx
src/utils/api/authAPI.ts
src/utils/getCallBackURL.ts

자유게시판 fixed넓이조정
소셜로그인(배포,local)
#327 
closed #327 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#327 [rafactor]: 자유게시판 fixed넓이조정및 소셜로그인(배포,local)

---

src/utils/api/authAPI.ts
src/utils/getCallBackURL.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#327 [fix]:배포로 재설정

---

src/components/my-clubs/info/HomeTab.tsx

mb-[78px]줬다..
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

스크롤 끝까지 안내려가는 문제해결

---

src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
src/app/(navigationBar)/my-clubs/page.tsx
src/app/(navigationBar)/mypage/mybookclubs/page.tsx
src/app/(navigationBar)/mypage/mysentences/page.tsx
src/app/(navigationBar)/mypage/page.tsx
src/common/Button.tsx
src/components/mypage/clubs/AllMyBookClubs.tsx
src/components/mypage/clubs/BookClubItem.tsx
src/components/mypage/clubs/MyBookClub.tsx
src/components/mypage/profile/Profile.tsx
src/components/mypage/profile/ProfileDetail.tsx
src/components/mypage/sentences/SentenceItem.tsx
src/hooks/info/useMyClubInfo.tsx
src/hooks/mypage/useUserClubs.tsx
src/utils/userAPIs/storageAPI.ts

닉네임 없을때 저장 막기,버튼 색 변경, BackBtn사용, 북클럽 archive false만 뜨게하기 , 왠지모르겠는데 storageAPI 초기로 돌아간거 다시 돌려놓음 마이페이지 글씨 색 변경 등등등.........^^...........ㅋㅋ
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix]:닉네임 없을때 저장 막기,버튼 색 변경, BackBtn사용 등등..

---

src/app/(navigationBar)/bookclubs/layout.tsx
src/app/(navigationBar)/my-clubs/layout.tsx
src/app/(navigationBar)/mypage/layout.tsx
src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
src/app/(navigationBar)/readbook/page.tsx
src/common/ToastUi.tsx

[fix] - 10분이내에 재 모임시작시 alert->toast로 변경 , 공통 컴포넌트toast : duration prop으로 받게 변경 , archive true되었을 때,  alert창 toastui로 변경
toast 컴포넌트 사용되는 곳에 duration프롤 넣어야됩니다~~~~
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - [fix] - 10분이내에 재 모임시작시 alert->toast로 변경 , 공통 컴포넌트toast : duration prop으로 받게 변경 , archive true되었을 때,  alert창 toastui로 변경

---

src/components/login/LoginForm.tsx
src/components/my-clubs/sentences/SentenceModal.tsx
src/components/register/RegisterForm.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#327 [fix]: ToastUi duration수정

---

src/components/mypage/clubs/BookClubItem.tsx
src/components/mypage/profile/ProfileDetail.tsx

콘솔제거, 북클럽이름길때 수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

콘솔제거, 북클럽이름길때 수정

---

src/app/(navigationBar)/bookclubs/[id]/JoinBtn.tsx

[style] : 참가하기 버튼 크기 수정

---

src/app/(navigationBar)/bookclubs/[id]/JoinBtn.tsx

[style] : 참가하기 버튼 안 옹졸하게 바꿈

---

src/app/login/page.tsx
src/common/Input.tsx
src/components/login/LoginForm.tsx
src/utils/api/authAPI.ts

login폼 toastUI->validate
#342 
closed #342 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-#342 [rafactor]: login폼 toastUI->validate

---

src/app/(navigationBar)/bookclubs/create/page.tsx
src/app/auth/authAPI.ts

소셜로그인시에 닉네임 이름으로 일단 넣어놓음
#358 
closed #358 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-Feature/#358

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/components/login/LoginForm.tsx
src/components/register/RegisterForm.tsx
src/utils/api/authAPI.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]- Feature/#375

---

src/app/(navigationBar)/mypage/page.tsx
src/components/mypage/clubs/BookClubItem.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[design]: 내 북클럽 이름과 화살표 사이 간격 수정

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/EndModal.tsx

[design]-북클럽 방장이 책 읽기 시작시 멤버들에게 알림간다고 toast, 모달창 높이수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#384 [design]-북클럽 방장이 책 읽기 시작시 멤버들에게 알림간다고 toast, 모달창 높이수정

---

src/app/(navigationBar)/bookclubs/layout.tsx
src/app/(navigationBar)/my-clubs/layout.tsx
src/app/(navigationBar)/mypage/layout.tsx
src/app/(navigationBar)/readbook/[id]/BookInfo.tsx

배포에 지속시간 잘못올려서 빠르게수정~~~
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #384 [mod] - 알림 지속시간 수정

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/page.tsx
src/app/chat/[id]/page.tsx
src/components/realtime/ChatInfo.tsx

채팅 tab으로 변경
#375 
closed #375 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-Feature/#375

---

src/app/(navigationBar)/readbook/ClubList.tsx
src/app/(navigationBar)/readbook/[id]/CompleteModal.tsx
src/app/(navigationBar)/readbook/[id]/EndModal.tsx
src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
src/app/chat/[id]/ChatInput.tsx
src/store/messages.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#389 [fix]-타이머 1:00:00->0:00:00 내려가게 수정,0:00:00때 완료모달, 책 읽기 다시시작하면 1:00:00으로 다시 스타트

---

src/app/(navigationBar)/mypage/mybookclubs/page.tsx
src/app/(navigationBar)/mypage/mysentences/page.tsx
src/components/my-clubs/info/HomeTab.tsx
src/components/mypage/profile/ProfileDetail.tsx

[fix]-북클럽요일 추가함요

---

src/app/(navigationBar)/bookclubs/layout.tsx
src/app/(navigationBar)/my-clubs/layout.tsx
src/components/my-clubs/board/Board.tsx
src/components/my-clubs/info/ClubBook.tsx
src/hooks/info/useMyClubInfo.tsx
src/utils/userAPIs/authAPI.ts

#390 
getuser 함수가 여러번 호출되어 waterfall 현상이 생기고 있었습니다
한 번만 호출되게 막았음
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: my-clubs 페이지의 getUser함수 요청 줄이기

---

src/components/mypage/sentences/AllMySentences.tsx
src/components/mypage/sentences/MySentencesStore.tsx
src/components/mypage/sentences/SentenceItem.tsx
src/hooks/mypage/useUserSentences.tsx

useUserSentence 조인으로변경
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[refactor]: 문장가져오는부분 join으로변경함

---

src/app/(navigationBar)/my-clubs/layout.tsx

유저id set추가
closed #408 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - [fix] - 유저id set추가

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/chat/[id]/ChatInput.tsx
src/app/globals.css
src/components/realtime/ChatBackImg.tsx
src/components/realtime/ChatMessages.tsx
src/components/realtime/ChatPresence.tsx
src/components/realtime/ListMessages.tsx
src/components/realtime/OtherMessage.tsx

채팅tab다시 css구현및 리팩토링
#393 
closed #393 
어떤 변경 사항이 있나요?
채팅tab다시 css구현및 리팩토링
```
|기능|스크린샷|
```

[철균]-#393 [rafactor]:채팅tab다시 css구현및 리팩토링

---

src/app/(navigationBar)/readbook/[id]/MemberList.tsx
src/components/realtime/ChatBackImg.tsx
src/components/realtime/ChatPresence.tsx

불필요코드제거
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-Feature/#393

---

src/app/(navigationBar)/readbook/ClubList.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[fix] - 핫픽스 링크 필터링 이슈;;

---

src/app/layout.tsx
src/components/my-clubs/info/HomeTab.tsx
src/components/my-clubs/info/Members.tsx
src/hooks/info/useMyClubInfo.tsx

#419 [refactor]: 멤버들가져올때 프로필도 같이 가져옴
closed #419 
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

 [refactor]: 멤버들가져올때 프로필도 같이 가져옴

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/MemberList.tsx
src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
src/app/(navigationBar)/readbook/[id]/page.tsx
src/utils/testAPIs.ts
src/utils/userAPIs/authAPI.ts

#390 
readbook/[id] 페이지 성능 개선 했습니다..!
save 페이지도 필요합니다
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: readbook [id]페이지 성능 개선

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/MemberList.tsx
src/app/(navigationBar)/readbook/[id]/page.tsx

dev야 아프지마
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[승희]: dev 테스트

---

.vscode/extensions.json
src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/page.tsx
src/app/chat/[id]/ChatInput.tsx
src/app/chat/[id]/page.tsx
src/components/realtime/ChatBackImg.tsx
src/components/realtime/ChatInfo.tsx
src/components/realtime/ChatMessages.tsx
src/components/realtime/ListMessages.tsx
src/components/realtime/LoadMoreMessages.tsx
src/components/realtime/OtherMessage.tsx
src/store/messages.ts

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[철균]-Feature/#418

---

src/components/my-clubs/info/ClubBook.tsx

mb-4 추가함
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[design]:mb-4수정

---

src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/chat/[id]/ChatInput.tsx

배포테스트(도메인변경)
#436 
closed #436 
어떤 변경 사항이 있나요?
배포테스트(도메인변경)
```
|기능|스크린샷|
```

배포테스트(도메인변경)

---

src/app/(navigationBar)/readbook/ClubList.tsx
src/app/(navigationBar)/readbook/ProgressBar.tsx
src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
src/app/(navigationBar)/readbook/page.tsx
src/app/layout.tsx
src/lib/types/supabase.ts
src/utils/userAPIs/authAPI.ts

[fix]-모바일 스크롤테스트, 책읽기 페이지추가,스타일수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연]-#408 [fix]-모바일 스크롤테스트, 책읽기 페이지추가,스타일수정

---

src/app/(navigationBar)/readbook/ClubList.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

fix-배포에러수정

---

src/app/(navigationBar)/bookclubs/create/page.tsx

개설하기 페이지 디자인 변경
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[현미] - Style/#440 개설하기 페이지 디자인 변경

---

src/app/(navigationBar)/readbook/ClubList.tsx

어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[대연] - #408[design] - 표지 디자인변경

---

src/app/globals.css

스크롤바없애기 테스트
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

[test]: 스크롤바없애기 테스트

---

src/app/(navigationBar)/readbook/ClubList.tsx
src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
src/app/(navigationBar)/readbook/[id]/MemberList.tsx

[fix] - 책 읽기 높이 수정, 독서중 수정
어떤 변경 사항이 있나요?
```
|기능|스크린샷|
```

#408 [fix] - 책 읽기 높이 수정, 독서중 수정
